name = "astro-agency-starter"
pages_build_output_dir = "dist"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]


# Cloudflare account (sulimierski.jakub@gmail.com)
# account_id = "c08a11ec88e62b32f91afc2c83b4c687"

[[d1_databases]]
binding = "DB"
database_name = "astro-agency-starter"
database_id = "f1bbf4e0-9224-4fd4-afce-3fc163dd6ead"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "astro-agency-starter-bucket"
